### ISSUE TITLE
ImageCat Streaming

### ISSUE THREAD

**Issue by scambria** [chrismattmann/imagecat#34]
For integrating ImageCat into the Memex crawler pipeline, we would like to run the integration code in Storm for real-time processing. Is it possible to provide a streaming API for ImageCat? 

Thanks,
Steve

**Comment by lewismc** [comment]
Thanks @scambria @chrismattmann we are able to stream data into Imagecat via the OODT streaming work 
https://cwiki.apache.org/confluence/display/OODT/A+Guide+to+Streaming+OODT
I think we should have a look at building the componenets into Radix (also upgrade to OODT 0.11-SNAPSHOT?) and to have the build configurable. Maybe Maven profiles might work here?

**Comment by chrismattmann** [comment]
yep, we have been thinking about this @scambria . Thanks @lewismc for providing this link.

**Comment by chrismattmann** [comment]
Using the [Docker](https://github.com/chrismattmann/imagecat/tree/master/DOCKER) script, you can continuously add images to the watch file, and it will ingest/update them. That's as close to streaming as we're going to support for now.
