### ISSUE TITLE
deploy/bin/env.sh sets spurious environment variable on line 48 

### ISSUE THREAD

**Issue by Coldsp33d** [chrismattmann/imagecat#40]
Professor,

In the process of seting up imagecat, I found a bug. This occurs once you're run `./install.sh`, and are in the process of running `./start.sh` inside deploy.

On line 47 of /bin/env.sh, there is 

    export OODT_HOME=--OODT_HOME--

Which interferes with the startup process and should be removed. We're already setting `OODT_HOME` in `bin/imagecatenv.sh`, so this line can either be removed, or edited to take the value from `imagecatenv.sh`.

Similarly, another file contains the same substring `tomcat7/conf/Catalina/localhost/solr.xml`.

For reference, I found these files by running the command

    egrep -ril '\-\-OODT_HOME\-\-' .  

Inside the `deploy` folder.

**Comment by chrismattmann** [comment]
Fixed in #41
