### ISSUE TITLE
pysolr not in docker container

### ISSUE THREAD

**Issue by adidier17** [chrismattmann/imagecat#44]
There is an ImportError when running sha1sum.py from /deploy/pge/bin/sha1sum inside the docker container. 

http://localhost:8081/solr/imagecatdevge/bin/sha1sum && python2.7 sha1sum.py -s  
Traceback (most recent call last):
  File "sha1sum.py", line 24, in <module>
    import pysolr
ImportError: No module named pysolr

**Comment by chrismattmann** [comment]
perfect, fixed @adidier17
